### ISSUE TITLE
'It's not clear which file to import' error message

### ISSUE THREAD

**Issue by ivostork** [chriseppstein/sass-globbing#3]
Hey,
I've changed my imports from this"

@import "extensions/content/css-hack";
@import "extensions/content/grid";
@import "extensions/content/media";
@import "extensions/content/misc";
@import "extensions/content/table";
@import "extensions/content/mod";
@import "extensions/content/forms";

to this:

@import "extensions/content/*";

Added require 'sass-globbing' to config.rb

but I am getting this message when compiling..

It's not clear which file to import for '@import"extensions/content/*"'.
 Candidates:
   extensions/content/_css-hack.scss
   extensions/content/_forms.scss
   extensions/content/_grid.scss
   extensions/content/_media.scss
   extensions/content/_misc.scss
   extensions/content/_mod.scss
   extensions/content/_oocssgrid.scss
   extensions/content/_table.scss
 For now I'll choose _css-hack.scss.
 This will be an error in future versions of Sass

Any ideas what could be wrong here?

This is my gem list
*** LOCAL GEMS ***

addressable (2.2.6)
chunky_png (1.2.4)
compass (0.12.2)
compass-validator (3.0.1)
css_parser (1.2.5)
fssm (0.2.7)
minitest (1.6.0)
modular-scale (1.0.2, 1.0.1)
rake (0.8.7)
rdoc (2.5.8)
sass (3.2.2, 3.2.0.alpha.247)
sass-globbing (1.0.0)
sassy-math (1.2)
susy (1.0.rc.4)
webfontspecimen (0.3.0)

**Comment by amitmtrn** [comment]
does anyone succeed in fixing this issue?
I tried
```
@import "components/*.*";
```
and I get this error
```
"Error: File to import not found or unreadable: components/_background-catalog.scss.\A Load paths:\A bower_components\A c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/compass-core-1.1.0.alpha.3/stylesheets\A Compass::SpriteImporter\A Sass::Globbing::Importer\A on line 1 of app/styles/components/*.*\A from line 7 of app/styles/main.scss\A \A 1: @charset \"utf-8\";\A 2: @import \"compass\";\A 3: @import \"reset\";\A 4: @import \"global\";\A 5: @import \"icons\";\A 6: @import \"fonts\";"
```

**Comment by Dan503** [comment]
I'm getting the same issue as amitmtrn

> "Error: File to import not found or unreadable: ...

**Comment by Dan503** [comment]
Hi, I've got a work around for this for anyone still having the issue.

https://github.com/DennisBecker/grunt-sass-globbing

Basically you create a file (an import map) that holds all your @imports and then let grunt will fill it in with all the actual specific import paths for you. It's a little messier than if SASS just let you bulk import on it's own but it's guaranteed to work since sass will only be reading imports to specific files, grunt is the one that reads the "sass/*.scss" stuff.

**Comment by maple-leaf** [comment]
still not working.
sass v3.4.11
compass v1.0.3
sass-globbing v1.1.1
win8 64

**Comment by LPGhatguy** [comment]
I'm getting this issue when there's only one file in the folder as well. Has there been *any* progress on the problem?

```
main.scss (Line 6: It's not clear which file to import for '@import "sections/*"'.
Candidates:
  sections/_header.scss
  sections/_header.scss
Please delete or rename all but one of these files.
```

**Comment by dougcassidy** [comment]
dont work: `@import 'partials/*';`

works:
`@import 'partials/**/*';`
note the 2 stars, then 1 star.

**Comment by markentingh** [comment]
I cannot believe this issue is still open after THREE YEARS! This issue is a breaking issue and should have been fixed in January 2013, but here it is, end of February 2016, and I STILL can't compile a SASS project in Windows that works on just fine in Linux. FIX THIS RIGHT NOW!!!!!

I am very disappointed to find out that in order for me to compile a SASS project on Windows, I have to change all * into **/* or *.* or some bullshit, which then needs to be CHANGED BACK to its original format before committing my changes so my team mates (who use Linux) can also compile the same SASS project on their machines. What a joke! I would rather use LESS than this crappy SASS globbing bullshit.

**Comment by LPGhatguy** [comment]
@markentingh Your team also has the option of moving to libsass (either sassc or node-sass) which has more options for import customization. It's right around on-par with Ruby Sass 3.4 now.

**Comment by markentingh** [comment]
that would require me to tell my team to rewrite their gulp files... honestly, I want this to be fixed for good, because the world needs this to be fixed. It's so frustrating walking into this problem over and over again, having to rewrite the SASS imports code for every project that uses SASS. It's just bullshit that no one has tackled this problem. Will no one claim responsibility?

**Comment by Dan503** [comment]
Did you look into my post about a workaround?
https://github.com/DennisBecker/grunt-sass-globbing

It's messy but it works across all platforms.
I'm not sure if there is a gulp version out there though.

**Comment by markentingh** [comment]
Thank you for your help, @Dan503... It's a sad state of sass-globbing affairs, isn't it? It could so easily be fixed, and if only I could get to the heart of the problem in this open source project, I would fix it myself. This issue seems to be on the same level as ending world hunger (apparently). Guess I'll just have to install Virtual Box, Vagrant, and run Linux in Windows to accomplish what I'm trying to do...

**Comment by chriseppstein** [comment]
>  I would rather use LESS than this crappy SASS globbing bullshit.

Please do. Or maybe don't use globbing. Or fork it. Really, do anything you want, but yelling on my issue tracker to fix a thing that isn't even *required* for you to use, makes you a much bigger jerk than me for not maintaining a thing that I haven't used for coming on three years.

**Comment by chriseppstein** [comment]
Please test with 1.1.3 or greater and file a new issue if one still exists.
